// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HansOrtizExamenProgreso1.Migrations
{
    [DbContext(typeof(HansOrtizExamenProgreso1Context))]
    [Migration("20241028144430_InicioExamenHansOrtiz")]
    partial class InicioExamenHansOrtiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HansOrtizExamenProgreso1.Models.HO_Producto", b =>
                {
                    b.Property<int>("HO_ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HO_ProductoId"));

                    b.Property<DateTime?>("HO_CreateAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HO_Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HO_ProductoDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HO_ProductoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HO_Variantes")
                        .HasColumnType("bit");

                    b.HasKey("HO_ProductoId");

                    b.ToTable("HO_Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
